### ISSUE TITLE
extend MonologServiceProvider

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/CilexServiceProviders#34]
add some processors, show integration with symfony/monolog-bridge, extend config
```yaml
monolog:
   processors:
       some:
           class: ...
```
