### ISSUE TITLE
support callable as array of commands

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/CilexServiceProviders#93]
https://github.com/kamilsk/CilexServiceProviders/blob/master/docs/AppAndCommands.md#configuration-example

**Comment by kamilsk** [comment]
Required example in [Click](https://github.com/octolab/Click):
```yaml
cli_menu:
  title: %app_name% Menu
  items:
  - text: Install demo content
    commands:
    - { name: "click:set", options: { env: demo, urn: /click, url: https://github.com/octolab/Click, alias: click } }
    - { name: "click:set", options: { env: demo, urn: /google, url: https://www.google.com/ } }
    - { name: "click:set", options: { env: demo, urn: /yandex, url: http://www.yandex.ru/ } }
    - { name: "click:remove", options: { env: demo, urn: /google } }
```
